### ISSUE TITLE
Add support for scaleway_rdb_database

### ISSUE THREAD

**Issue by tbobm** [particuleio/terraform-scaleway-database#10]
Create the corresponding managed databases for each rdb instance.

See https://registry.terraform.io/providers/scaleway/scaleway/latest/docs/resources/rdb_database

**Todos**
- [ ] Add support for the `.database.managed_dbs` argument
- [ ] Add default `[]` in `locals.tf`
- [ ] Output the created `scaleway_rdb_database` resources
- [ ] Update README (add `database` to supported components)
